Technical improvements
City-of-Helsinki/django-munigeo pull request #35
Opened 2020-12-28 09:22 UTC by a-rmz

## Description :sparkles:
- Remove Python 2 compatibility
- Upgrade and pin django-parler version
  - Add the migration required for the new parler version
- Remove naive timestamp warning
- Version bump (`0.4.0-beta`)

## Additional notes :spiral_notepad:
Some additional changes were made to `djanog-mptt` (disabling some indexes), so those changes are also reflected on the migration.

2020-12-29 08:39 UTC, tuomas777 commented on munigeo/migrations/0001_squashed_0004_building.py
> +            field=models.DateTimeField(auto_now=True, default=datetime.datetime(1970, 1, 1, 2, 0, tzinfo=datetime.timezone.utc), help_text='Time when the information was last changed'),
I think these defaults could be just removed. There shouldn't be any need to have both `auto_now` and `default` unless there is some existing data in the models when running the migration, which should not be possible because this is the first migration.

2020-12-29 08:39 UTC, tuomas777 commented on setup.py
> +    version='0.4.0-beta',
The version situation in munigeo seems to be a bit tangled ATM. If I've not mistaken there are versions `0.2.x` which use Modeltranslation and versions `0.3.x` which use Parler, and both are developed actively. So not sure how that should be handled and whether this should be `0.4.x` or something else. Maybe @Rikuoja has an opinion on this?

2023-01-19 13:22 UTC, mhieta commented on setup.py
> +    version='0.4.0-beta',
Agreed, that let's use 0.3.7 for now here.

2023-01-19 13:29 UTC, mhieta requested changes
@jakezu Please fix the default value.

2023-01-19 13:29 UTC, mhieta commented on munigeo/migrations/0001_squashed_0004_building.py
> +            field=models.DateTimeField(auto_now=True, default=datetime.datetime(1970, 1, 1, 2, 0, tzinfo=datetime.timezone.utc), help_text='Time when the information was last changed'),
@jakezu Please fix this, so remove these defaults completely.

2023-01-19 14:13 UTC, mhieta approved these changes
Good for now

2023-01-19 14:15 UTC, merged