Add view and serializer for PostalCodeArea
City-of-Helsinki/django-munigeo pull request #42
Opened 2022-03-21 12:55 UTC by juuso-j

# View and Serializer for PostalCodeArea

### Breakdown

1. munigeo/api.py
    * Added serializer and view for PostalCodeAreas and postalcodearea field for Addresses.

2022-03-21 14:48 UTC, mhieta requested changes
Fix typos. Otherwise looks good.

2022-03-21 14:48 UTC, mhieta commented on munigeo/api.py
> +class PostlCodeSerializer(TranslatedModelSerializer):
Fix typo here

2022-03-21 14:48 UTC, mhieta commented on munigeo/api.py
> +        ret['postal_code_area'] = PostlCodeSerializer(obj.postal_code_area).data
Typo here also

2022-03-22 06:33 UTC, juuso-j commented on munigeo/api.py
> +class PostlCodeSerializer(TranslatedModelSerializer):
Fixed.

2022-03-22 06:33 UTC, juuso-j commented on munigeo/api.py
> +        ret['postal_code_area'] = PostlCodeSerializer(obj.postal_code_area).data
Fixed.

2022-03-23 05:20 UTC, mhieta approved these changes
LGTM 👍

2022-03-23 05:20 UTC, merged